W7D3/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:show, :new, :create]
end

W7D3/music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  
  
end

W7D3/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, uniqueness: true
  validates :password_digest, length: { minimum: 6, allow_nil: true }
  validates :email, :password_digest, :session_token, presence: true

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    user && user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    token = SecureRandom.urlsafe_base64(16)

    # while self.class.exists?(session_token: token)
    #   token = SecureRandom.urlsafe_base64(16)
    # end

    token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

W7D3/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

end

W7D3/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if user.nil?
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    else
      log_in_user!(user)
      redirect_to user_url(user.id)
    end

  end

  def new
    render :new
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil

    redirect_to new_session_url
  end

end

W7D3/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])

    render :show
  end

  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_session_url
    else
      render :new
    end
  end

  private
  def user_params
    self.params.require(:user).permit(:email, :password)
  end
end

W7D3/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W7D3/music_app/app/helpers/users_helper.rb
module UsersHelper
end

W7D3/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='main-content'>
      <h1 class='main-logo'>Music App</h1>
      <% if logged_in? %>
      <nav>
        <div class='user-detail'>
          <p>Logged in as: <%= current_user.email %></p>
        <form action=<%= session_url %> method='post'>
          <input type="hidden" name="_method" value="delete">
          <input type="hidden" name="authencity_token" value="<%= form_authenticity_token %>">
          <input type="submit" value="Sign Out">
        </div>
      </nav>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

W7D3/music_app/app/views/users/new.html.erb
<h1 class='page-header'>New User</h1>

<a class='button' href=<%= new_session_url %> >Go to sign-in</a>

<form class='form' action="<%= users_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='new-user-email'>Email</label>
    <input id='new-user-email' type="text" name="user[email]">
  </p>

  <p>
    <label for='new-user-password'>Password</label>
    <input id='new-user-password' type="password" name="user[password]">
  </p>

  <input type="submit" value="Submit">
</form>

W7D3/music_app/app/views/users/show.html.erb
<h1 class='page-header'>User Profile</h1>
<p>
  Email: <%= current_user.email %>
</p>